### ISSUE TITLE
Blank ad unit

### ISSUE THREAD

**Issue by amd64fox** [R3nzTheCodeGOD/Spotify-Internal#1]
Hello, thank you very much for the patch, everything works except for this empty block, do you have any ideas how to remove it?
![115572142-4c2b5800-a2c8-11eb-9937-fdcff064105e 1](https://user-images.githubusercontent.com/62529699/126732319-3c153ae4-24c6-484c-879b-2b0975cee3c9.jpg)

**Comment by R3nzTheCodeGOD** [comment]
maybe it can be fixed

**Comment by R3nzTheCodeGOD** [comment]
I have a workaround that works for now.

1. Navigate to **%APPDATA%/Spotify/Apps**. Here you will find xpui.spa, make a copy of this file so that you have a backup.
2.  Rename **xpui.spa** to **xpui.zip** and open the zip. Within the zip, there will be xpui.css, extract this file.
3. Open the extracted file with a text editor and search for **.b2731cdeb97c1f6a4cf5caa44e943acb-scss** This is the css selector of the ad banner div.
4. For this selector, change the **display:flex** to **display:none**, save the file, drop it back in the zip to replace the original xpui.css.
5. Change the extension from **xpui.zip** to **xpui.spa**

![image](https://user-images.githubusercontent.com/58574988/126763102-98e7cf0a-302c-429e-8a7b-c41740f20588.png)

**Comment by amd64fox** [comment]
Thank you, I have already seen about manual editing of these files, I mean, is it possible to remove this automatically via installer.bat?

**Comment by R3nzTheCodeGOD** [comment]
**[This](https://github.com/Kibakus/SpotifyBlockNewUI/blob/main/spotify.py) python script is extremely fast and works well.**

**Comment by R3nzTheCodeGOD** [comment]
updated the last update I converted the script to exe

**Comment by amd64fox** [comment]
Great, but you can combine it all into one file, for convenience? So as not to run the noAdsScript.exe and installer.bat files separately

**Comment by R3nzTheCodeGOD** [comment]
Yes, it can be converted to .bat, but I'm a little unsuccessful in writing batch script. For me, running 2 separate programs is quite enough and easy.
